/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 */

#include "gosh.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t TimeStamp_fields[3] = {
    PB_FIELD(  1, INT64   , REQUIRED, STATIC  , FIRST, TimeStamp, seconds, seconds, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, TimeStamp, nanos, seconds, 0),
    PB_LAST_FIELD
};

const pb_field_t RunCommand_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, RunCommand, command, command, 0),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, RunCommand, exec_time, command, &TimeStamp_fields),
    PB_LAST_FIELD
};

const pb_field_t RunScriptCommand_fields[5] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, RunScriptCommand, script, script, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, RunScriptCommand, stack_size, script, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, RunScriptCommand, priority, stack_size, 0),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, RunScriptCommand, exec_time, priority, &TimeStamp_fields),
    PB_LAST_FIELD
};

const pb_field_t ListJobsCommand_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t StopCommand_fields[2] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, StopCommand, exec_time, exec_time, &TimeStamp_fields),
    PB_LAST_FIELD
};

const pb_field_t ShellCommand_fields[3] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, ShellCommand, stack_size, stack_size, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, ShellCommand, priority, stack_size, 0),
    PB_LAST_FIELD
};

const pb_field_t KeepAlive_fields[2] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, KeepAlive, time, time, &TimeStamp_fields),
    PB_LAST_FIELD
};

const pb_field_t ResultTuple_fields[4] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, ResultTuple, group, group, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, ResultTuple, key, group, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, ResultTuple, value, key, 0),
    PB_LAST_FIELD
};

const pb_field_t CommandResponse_fields[5] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, CommandResponse, results, results, &ResultTuple_fields),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, CommandResponse, return_code, results, 0),
    PB_FIELD(  3, BOOL    , REQUIRED, STATIC  , OTHER, CommandResponse, completion_flag, return_code, 0),
    PB_FIELD( 10, STRING  , OPTIONAL, STATIC  , OTHER, CommandResponse, std_out, completion_flag, 0),
    PB_LAST_FIELD
};

const pb_field_t GoshRequest_fields[8] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, GoshRequest, id, id, 0),
    PB_ONEOF_FIELD(command,  10, MESSAGE , ONEOF, STATIC  , OTHER, GoshRequest, run, id, &RunCommand_fields),
    PB_ONEOF_FIELD(command,  11, MESSAGE , ONEOF, STATIC  , UNION, GoshRequest, runscript, id, &RunScriptCommand_fields),
    PB_ONEOF_FIELD(command,  12, MESSAGE , ONEOF, STATIC  , UNION, GoshRequest, listjobs, id, &ListJobsCommand_fields),
    PB_ONEOF_FIELD(command,  13, MESSAGE , ONEOF, STATIC  , UNION, GoshRequest, stop, id, &StopCommand_fields),
    PB_ONEOF_FIELD(command,  14, MESSAGE , ONEOF, STATIC  , UNION, GoshRequest, shell, id, &ShellCommand_fields),
    PB_ONEOF_FIELD(command,  15, MESSAGE , ONEOF, STATIC  , UNION, GoshRequest, keepalive, id, &KeepAlive_fields),
    PB_LAST_FIELD
};

const pb_field_t GoshResponse_fields[4] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, GoshResponse, id, id, 0),
    PB_ONEOF_FIELD(response,  10, MESSAGE , ONEOF, STATIC  , OTHER, GoshResponse, command, id, &CommandResponse_fields),
    PB_ONEOF_FIELD(response,  20, MESSAGE , ONEOF, STATIC  , UNION, GoshResponse, keepalive, id, &KeepAlive_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(RunCommand, exec_time) < 65536 && pb_membersize(RunScriptCommand, exec_time) < 65536 && pb_membersize(StopCommand, exec_time) < 65536 && pb_membersize(KeepAlive, time) < 65536 && pb_membersize(CommandResponse, results[0]) < 65536 && pb_membersize(GoshRequest, command.run) < 65536 && pb_membersize(GoshRequest, command.runscript) < 65536 && pb_membersize(GoshRequest, command.listjobs) < 65536 && pb_membersize(GoshRequest, command.stop) < 65536 && pb_membersize(GoshRequest, command.shell) < 65536 && pb_membersize(GoshRequest, command.keepalive) < 65536 && pb_membersize(GoshResponse, response.command) < 65536 && pb_membersize(GoshResponse, response.keepalive) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_TimeStamp_RunCommand_RunScriptCommand_ListJobsCommand_StopCommand_ShellCommand_KeepAlive_ResultTuple_CommandResponse_GoshRequest_GoshResponse)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for CommandResponse.std_out is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
