#ifndef APP_VERSION_H
#define APP_VERSION_H

#define APP_VERSION_MAJOR  1
#define APP_VERSION_MINOR  0
#define APP_VERSION_PATCH  0
#define APP_VERSION_STR    "1.0.0"
#define APP_BUILD_NUMBER   74

#endif /* APP_VERSION_H */
